export default  {
    candidate: `
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a mauris lorem. Vestibulum malesuada, dui ut dictum congue, ipsum metus vestibulum tellus, eget tincidunt ante augue et odio. Vestibulum scelerisque vitae nisi quis efficitur. Morbi hendrerit neque iaculis tempor blandit. Ut lobortis ullamcorper diam, eget ullamcorper felis scelerisque quis. Nullam vehicula nibh eu augue pellentesque, nec pretium massa congue. Sed quis neque ut arcu interdum efficitur ut eu magna. Nulla egestas elementum nisi, pulvinar blandit lacus pellentesque sed. Cras eget urna ipsum. Aliquam euismod risus eget quam rutrum, sit amet placerat elit lobortis. Etiam imperdiet imperdiet semper.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a mauris lorem. Vestibulum malesuada, dui ut dictum congue, ipsum metus vestibulum tellus, eget tincidunt ante augue et odio. Vestibulum scelerisque vitae nisi quis efficitur. Morbi hendrerit neque iaculis tempor blandit. Ut lobortis ullamcorper diam, eget ullamcorper felis scelerisque quis. Nullam vehicula nibh eu augue pellentesque, nec pretium massa congue. Sed quis neque ut arcu interdum efficitur ut eu magna. Nulla egestas elementum nisi, pulvinar blandit lacus pellentesque sed. Cras eget urna ipsum. Aliquam euismod risus eget quam rutrum, sit amet placerat elit lobortis. Etiam imperdiet imperdiet semper.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a mauris lorem. Vestibulum malesuada, dui ut dictum congue, ipsum metus vestibulum tellus, eget tincidunt ante augue et odio. Vestibulum scelerisque vitae nisi quis efficitur. Morbi hendrerit neque iaculis tempor blandit. Ut lobortis ullamcorper diam, eget ullamcorper felis scelerisque quis. Nullam vehicula nibh eu augue pellentesque, nec pretium massa congue. Sed quis neque ut arcu interdum efficitur ut eu magna. Nulla egestas elementum nisi, pulvinar blandit lacus pellentesque sed. Cras eget urna ipsum. Aliquam euismod risus eget quam rutrum, sit amet placerat elit lobortis. Etiam imperdiet imperdiet semper.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a mauris lorem. Vestibulum malesuada, dui ut dictum congue, ipsum metus vestibulum tellus, eget tincidunt ante augue et odio. Vestibulum scelerisque vitae nisi quis efficitur. Morbi hendrerit neque iaculis tempor blandit. Ut lobortis ullamcorper diam, eget ullamcorper felis scelerisque quis. Nullam vehicula nibh eu augue pellentesque, nec pretium massa congue. Sed quis neque ut arcu interdum efficitur ut eu magna. Nulla egestas elementum nisi, pulvinar blandit lacus pellentesque sed. Cras eget urna ipsum. Aliquam euismod risus eget quam rutrum, sit amet placerat elit lobortis. Etiam imperdiet imperdiet semper.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a mauris lorem. Vestibulum malesuada, dui ut dictum congue, ipsum metus vestibulum tellus, eget tincidunt ante augue et odio. Vestibulum scelerisque vitae nisi quis efficitur. Morbi hendrerit neque iaculis tempor blandit. Ut lobortis ullamcorper diam, eget ullamcorper felis scelerisque quis. Nullam vehicula nibh eu augue pellentesque, nec pretium massa congue. Sed quis neque ut arcu interdum efficitur ut eu magna. Nulla egestas elementum nisi, pulvinar blandit lacus pellentesque sed. Cras eget urna ipsum. Aliquam euismod risus eget quam rutrum, sit amet placerat elit lobortis. Etiam imperdiet imperdiet semper.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a mauris lorem. Vestibulum malesuada, dui ut dictum congue, ipsum metus vestibulum tellus, eget tincidunt ante augue et odio. Vestibulum scelerisque vitae nisi quis efficitur. Morbi hendrerit neque iaculis tempor blandit. Ut lobortis ullamcorper diam, eget ullamcorper felis scelerisque quis. Nullam vehicula nibh eu augue pellentesque, nec pretium massa congue. Sed quis neque ut arcu interdum efficitur ut eu magna. Nulla egestas elementum nisi, pulvinar blandit lacus pellentesque sed. Cras eget urna ipsum. Aliquam euismod risus eget quam rutrum, sit amet placerat elit lobortis. Etiam imperdiet imperdiet semper.
        
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a mauris lorem. Vestibulum malesuada, dui ut dictum congue, ipsum metus vestibulum tellus, eget tincidunt ante augue et odio. Vestibulum scelerisque vitae nisi quis efficitur. Morbi hendrerit neque iaculis tempor blandit. Ut lobortis ullamcorper diam, eget ullamcorper felis scelerisque quis. Nullam vehicula nibh eu augue pellentesque, nec pretium massa congue. Sed quis neque ut arcu interdum efficitur ut eu magna. Nulla egestas elementum nisi, pulvinar blandit lacus pellentesque sed. Cras eget urna ipsum. Aliquam euismod risus eget quam rutrum, sit amet placerat elit lobortis. Etiam imperdiet imperdiet semper.
    `,
    sponsor: `
        Mauris id augue arcu. Sed ullamcorper felis ut ante hendrerit rhoncus. Nulla cursus ex sed lacinia dapibus. Sed ac ex et nisi posuere vehicula. Suspendisse potenti. In hac habitasse platea dictumst. Nulla auctor faucibus diam, ac ornare mauris finibus at. Nulla in nulla nulla. Sed nulla neque, blandit sed ligula a, mattis tristique mi. Nunc lacinia, nisi pretium hendrerit interdum, sem lacus ultrices augue, in aliquam dui augue vel dolor. Morbi iaculis accumsan nisi a aliquam. Sed rutrum dapibus porttitor. Proin vulputate bibendum tortor, ac laoreet elit fermentum at. Donec tellus odio, accumsan at tempor ac, tempus ut est. Sed auctor vestibulum justo, hendrerit vestibulum ligula venenatis quis. Nam et felis at nibh sollicitudin commodo ut vel quam.
        
        Mauris id augue arcu. Sed ullamcorper felis ut ante hendrerit rhoncus. Nulla cursus ex sed lacinia dapibus. Sed ac ex et nisi posuere vehicula. Suspendisse potenti. In hac habitasse platea dictumst. Nulla auctor faucibus diam, ac ornare mauris finibus at. Nulla in nulla nulla. Sed nulla neque, blandit sed ligula a, mattis tristique mi. Nunc lacinia, nisi pretium hendrerit interdum, sem lacus ultrices augue, in aliquam dui augue vel dolor. Morbi iaculis accumsan nisi a aliquam. Sed rutrum dapibus porttitor. Proin vulputate bibendum tortor, ac laoreet elit fermentum at. Donec tellus odio, accumsan at tempor ac, tempus ut est. Sed auctor vestibulum justo, hendrerit vestibulum ligula venenatis quis. Nam et felis at nibh sollicitudin commodo ut vel quam.
        
        Mauris id augue arcu. Sed ullamcorper felis ut ante hendrerit rhoncus. Nulla cursus ex sed lacinia dapibus. Sed ac ex et nisi posuere vehicula. Suspendisse potenti. In hac habitasse platea dictumst. Nulla auctor faucibus diam, ac ornare mauris finibus at. Nulla in nulla nulla. Sed nulla neque, blandit sed ligula a, mattis tristique mi. Nunc lacinia, nisi pretium hendrerit interdum, sem lacus ultrices augue, in aliquam dui augue vel dolor. Morbi iaculis accumsan nisi a aliquam. Sed rutrum dapibus porttitor. Proin vulputate bibendum tortor, ac laoreet elit fermentum at. Donec tellus odio, accumsan at tempor ac, tempus ut est. Sed auctor vestibulum justo, hendrerit vestibulum ligula venenatis quis. Nam et felis at nibh sollicitudin commodo ut vel quam.
        
        Mauris id augue arcu. Sed ullamcorper felis ut ante hendrerit rhoncus. Nulla cursus ex sed lacinia dapibus. Sed ac ex et nisi posuere vehicula. Suspendisse potenti. In hac habitasse platea dictumst. Nulla auctor faucibus diam, ac ornare mauris finibus at. Nulla in nulla nulla. Sed nulla neque, blandit sed ligula a, mattis tristique mi. Nunc lacinia, nisi pretium hendrerit interdum, sem lacus ultrices augue, in aliquam dui augue vel dolor. Morbi iaculis accumsan nisi a aliquam. Sed rutrum dapibus porttitor. Proin vulputate bibendum tortor, ac laoreet elit fermentum at. Donec tellus odio, accumsan at tempor ac, tempus ut est. Sed auctor vestibulum justo, hendrerit vestibulum ligula venenatis quis. Nam et felis at nibh sollicitudin commodo ut vel quam.

        Nullam consectetur dui et tortor pharetra mattis ut vel ante. Integer mattis urna ac consequat dignissim. Nam odio magna, mollis porta maximus vel, iaculis a est. Donec iaculis, mi eget tincidunt vehicula, nulla felis ultrices turpis, eget cursus enim risus a urna. Proin eu libero velit. Mauris orci elit, maximus vel congue at, sollicitudin sed nunc. Nullam tincidunt justo sit amet massa vulputate venenatis.
        
        Nullam consectetur dui et tortor pharetra mattis ut vel ante. Integer mattis urna ac consequat dignissim. Nam odio magna, mollis porta maximus vel, iaculis a est. Donec iaculis, mi eget tincidunt vehicula, nulla felis ultrices turpis, eget cursus enim risus a urna. Proin eu libero velit. Mauris orci elit, maximus vel congue at, sollicitudin sed nunc. Nullam tincidunt justo sit amet massa vulputate venenatis.
        
        Nullam consectetur dui et tortor pharetra mattis ut vel ante. Integer mattis urna ac consequat dignissim. Nam odio magna, mollis porta maximus vel, iaculis a est. Donec iaculis, mi eget tincidunt vehicula, nulla felis ultrices turpis, eget cursus enim risus a urna. Proin eu libero velit. Mauris orci elit, maximus vel congue at, sollicitudin sed nunc. Nullam tincidunt justo sit amet massa vulputate venenatis.
        
        Nullam consectetur dui et tortor pharetra mattis ut vel ante. Integer mattis urna ac consequat dignissim. Nam odio magna, mollis porta maximus vel, iaculis a est. Donec iaculis, mi eget tincidunt vehicula, nulla felis ultrices turpis, eget cursus enim risus a urna. Proin eu libero velit. Mauris orci elit, maximus vel congue at, sollicitudin sed nunc. Nullam tincidunt justo sit amet massa vulputate venenatis.
        
        Nullam consectetur dui et tortor pharetra mattis ut vel ante. Integer mattis urna ac consequat dignissim. Nam odio magna, mollis porta maximus vel, iaculis a est. Donec iaculis, mi eget tincidunt vehicula, nulla felis ultrices turpis, eget cursus enim risus a urna. Proin eu libero velit. Mauris orci elit, maximus vel congue at, sollicitudin sed nunc. Nullam tincidunt justo sit amet massa vulputate venenatis.
    `,
    employer: `
        Quisque varius aliquet augue, ut blandit sem varius quis. Nunc ligula massa, fringilla vel aliquam sit amet, varius et enim. Nulla ultrices metus turpis, sed fermentum turpis tempus quis. Donec placerat volutpat nibh, at tincidunt erat lacinia vitae. Suspendisse ut convallis tortor. Nam rutrum viverra varius. Maecenas id sapien sed diam faucibus varius. Fusce ultrices auctor turpis in convallis. Nulla eget nisi at leo tempus volutpat. Aliquam gravida magna dolor. Curabitur non mauris porttitor, fermentum nisi a, luctus magna. Pellentesque non sodales purus. Pellentesque ut augue imperdiet, bibendum eros nec, dignissim metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi porta, orci eu tincidunt maximus, enim felis pretium nunc, ut aliquet ante risus in lectus. Duis mollis eget ligula non tempus.
        Quisque varius aliquet augue, ut blandit sem varius quis. Nunc ligula massa, fringilla vel aliquam sit amet, varius et enim. Nulla ultrices metus turpis, sed fermentum turpis tempus quis. Donec placerat volutpat nibh, at tincidunt erat lacinia vitae. Suspendisse ut convallis tortor. Nam rutrum viverra varius. Maecenas id sapien sed diam faucibus varius. Fusce ultrices auctor turpis in convallis. Nulla eget nisi at leo tempus volutpat. Aliquam gravida magna dolor. Curabitur non mauris porttitor, fermentum nisi a, luctus magna. Pellentesque non sodales purus. Pellentesque ut augue imperdiet, bibendum eros nec, dignissim metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi porta, orci eu tincidunt maximus, enim felis pretium nunc, ut aliquet ante risus in lectus. Duis mollis eget ligula non tempus.
        
        Quisque varius aliquet augue, ut blandit sem varius quis. Nunc ligula massa, fringilla vel aliquam sit amet, varius et enim. Nulla ultrices metus turpis, sed fermentum turpis tempus quis. Donec placerat volutpat nibh, at tincidunt erat lacinia vitae. Suspendisse ut convallis tortor. Nam rutrum viverra varius. Maecenas id sapien sed diam faucibus varius. Fusce ultrices auctor turpis in convallis. Nulla eget nisi at leo tempus volutpat. Aliquam gravida magna dolor. Curabitur non mauris porttitor, fermentum nisi a, luctus magna. Pellentesque non sodales purus. Pellentesque ut augue imperdiet, bibendum eros nec, dignissim metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi porta, orci eu tincidunt maximus, enim felis pretium nunc, ut aliquet ante risus in lectus. Duis mollis eget ligula non tempus.
        Quisque varius aliquet augue, ut blandit sem varius quis. Nunc ligula massa, fringilla vel aliquam sit amet, varius et enim. Nulla ultrices metus turpis, sed fermentum turpis tempus quis. Donec placerat volutpat nibh, at tincidunt erat lacinia vitae. Suspendisse ut convallis tortor. Nam rutrum viverra varius. Maecenas id sapien sed diam faucibus varius. Fusce ultrices auctor turpis in convallis. Nulla eget nisi at leo tempus volutpat. Aliquam gravida magna dolor. Curabitur non mauris porttitor, fermentum nisi a, luctus magna. Pellentesque non sodales purus. Pellentesque ut augue imperdiet, bibendum eros nec, dignissim metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi porta, orci eu tincidunt maximus, enim felis pretium nunc, ut aliquet ante risus in lectus. Duis mollis eget ligula non tempus.
        
        Pellentesque imperdiet, sem in sagittis malesuada, mi diam tempor felis, nec tempor neque enim ac augue. Aenean tempus nisi ac dui eleifend porta. Cras tempor nulla sed purus vestibulum, et ultrices metus porta. Suspendisse dignissim facilisis nisi, et euismod augue rutrum sed. Pellentesque quis est libero. Sed elementum congue lacus sit amet aliquam. Cras interdum scelerisque mauris viverra faucibus. Aenean et tincidunt mauris. Nam lobortis luctus finibus. Quisque id erat vulputate, luctus nibh ac, consequat velit. Nam urna tortor, ultricies ac purus ac, semper aliquam massa.
        
        Pellentesque imperdiet, sem in sagittis malesuada, mi diam tempor felis, nec tempor neque enim ac augue. Aenean tempus nisi ac dui eleifend porta. Cras tempor nulla sed purus vestibulum, et ultrices metus porta. Suspendisse dignissim facilisis nisi, et euismod augue rutrum sed. Pellentesque quis est libero. Sed elementum congue lacus sit amet aliquam. Cras interdum scelerisque mauris viverra faucibus. Aenean et tincidunt mauris. Nam lobortis luctus finibus. Quisque id erat vulputate, luctus nibh ac, consequat velit. Nam urna tortor, ultricies ac purus ac, semper aliquam massa.
        
        Pellentesque imperdiet, sem in sagittis malesuada, mi diam tempor felis, nec tempor neque enim ac augue. Aenean tempus nisi ac dui eleifend porta. Cras tempor nulla sed purus vestibulum, et ultrices metus porta. Suspendisse dignissim facilisis nisi, et euismod augue rutrum sed. Pellentesque quis est libero. Sed elementum congue lacus sit amet aliquam. Cras interdum scelerisque mauris viverra faucibus. Aenean et tincidunt mauris. Nam lobortis luctus finibus. Quisque id erat vulputate, luctus nibh ac, consequat velit. Nam urna tortor, ultricies ac purus ac, semper aliquam massa.
        Pellentesque imperdiet, sem in sagittis malesuada, mi diam tempor felis, nec tempor neque enim ac augue. Aenean tempus nisi ac dui eleifend porta. Cras tempor nulla sed purus vestibulum, et ultrices metus porta. Suspendisse dignissim facilisis nisi, et euismod augue rutrum sed. Pellentesque quis est libero. Sed elementum congue lacus sit amet aliquam. Cras interdum scelerisque mauris viverra faucibus. Aenean et tincidunt mauris. Nam lobortis luctus finibus. Quisque id erat vulputate, luctus nibh ac, consequat velit. Nam urna tortor, ultricies ac purus ac, semper aliquam massa.
        
        Pellentesque imperdiet, sem in sagittis malesuada, mi diam tempor felis, nec tempor neque enim ac augue. Aenean tempus nisi ac dui eleifend porta. Cras tempor nulla sed purus vestibulum, et ultrices metus porta. Suspendisse dignissim facilisis nisi, et euismod augue rutrum sed. Pellentesque quis est libero. Sed elementum congue lacus sit amet aliquam. Cras interdum scelerisque mauris viverra faucibus. Aenean et tincidunt mauris. Nam lobortis luctus finibus. Quisque id erat vulputate, luctus nibh ac, consequat velit. Nam urna tortor, ultricies ac purus ac, semper aliquam massa.
        
        Pellentesque imperdiet, sem in sagittis malesuada, mi diam tempor felis, nec tempor neque enim ac augue. Aenean tempus nisi ac dui eleifend porta. Cras tempor nulla sed purus vestibulum, et ultrices metus porta. Suspendisse dignissim facilisis nisi, et euismod augue rutrum sed. Pellentesque quis est libero. Sed elementum congue lacus sit amet aliquam. Cras interdum scelerisque mauris viverra faucibus. Aenean et tincidunt mauris. Nam lobortis luctus finibus. Quisque id erat vulputate, luctus nibh ac, consequat velit. Nam urna tortor, ultricies ac purus ac, semper aliquam massa.
    `
}